name: build

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/build.yml

jobs:
  android_luajit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build
        run: |
          cd build
          sudo apt-get update
          sudo apt install gcc-multilib libncurses5 -y
          ./make_android_luajit_arm64.sh  
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cd build
          ./make_linux64_luajit.sh
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit  
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cd build
          ./make_ios_luajit.sh
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
  osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cd build
          ./make_osx_luajit.sh
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit  
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build Luajit
        run: |
          cd build
          .\make_win64_luajit_gc64.bat
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
          
  windows-luajit-32:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Build Luajit
        run: |
          cd build
          .\make_win32_luajit.bat  
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
    
  windows-luabin:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build
        run: |
          cd build\luac
          .\make_win_lua51.bat
      - name: UploadLuabin51
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/bin_lua51/**/*
          name: bin_lua51
  windows-luabin-luajit-64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build Luajit
        run: |
          cd build\luac
          .\make_win64_luajit.bat 
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/bin_luajit/**/*
          name: bin_luajit
  windows-luabin-luajit-32:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Build Luajit
        run: |
          cd build\luac
          .\make_win32_luajit.bat  
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/bin_luajit/**/*
          name: bin_luajit
