name: publish

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

jobs:
  android_luajit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build
        run: |
          cd build
          sudo apt-get update
          sudo apt install gcc-multilib libncurses5 -y
          ./make_android_luajit_arm64.sh  
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
          
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cd build
          ./make_linux64_luajit.sh
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit  
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cd build
          ./make_ios_luajit.sh
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
  osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Build
        run: |
          cd build
          ./make_osx_luajit.sh
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit  
          
  windows-luajit-32:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Build Luajit
        run: |
          cd build
          .\make_win32_luajit.bat  
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
  windows-luajit-64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build Luajit
        run: |
          cd build
          .\make_win64_luajit.bat  
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit

  windows-luabin:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build
        run: |
          cd build\luac
          .\make_win_lua51.bat
      - name: UploadLuabin51
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/bin_lua51/**/*
          name: bin_lua51
  windows-luabin-luajit-64:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build Luajit
        run: |
          cd build\luac
          .\make_win64_luajit.bat 
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/bin_luajit/**/*
          name: bin_luajit
  windows-luabin-luajit-32:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Build Luajit
        run: |
          cd build\luac
          .\make_win32_luajit.bat  
      - name: UploadJit
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/bin_luajit/**/*
          name: bin_luajit

  publish:
    runs-on: ubuntu-latest
    needs: [osx,ios,android_luajit,linux,windows-luajit-32,windows-luajit-64,windows-luabin,windows-luabin-luajit-64,windows-luabin-luajit-32]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: plugin_luajit
          path: plugin_luajit/
          
      - uses: actions/download-artifact@v1
        with:
          name: bin_luajit
          path: bin_luajit/
          
      - uses: actions/download-artifact@v1
        with:
          name: bin_lua51
          path: bin_lua51/
          
      - name: Create Release Asset
        run: |
          cd plugin_luajit/ && tar cvfz ../luajit_${{ github.event.inputs.tag_name }}.tgz Plugins && cd -
          tar cvfz bin_luajit_${{ github.event.inputs.tag_name }}.tgz bin_luajit
          tar cvfz bin_lua51_${{ github.event.inputs.tag_name }}.tgz bin_lua51
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: Tag:${{ github.event.inputs.tag_name }}
          draft: false
          prerelease: false
          
      - name: Upload luajit Plugins
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./luajit_${{ github.event.inputs.tag_name }}.tgz
          asset_name: luajit_${{ github.event.inputs.tag_name }}.tgz
          asset_content_type: application/tgz
          
      - name: Upload luajit bin_luajit
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin_luajit_${{ github.event.inputs.tag_name }}.tgz
          asset_name: bin_luajit_${{ github.event.inputs.tag_name }}.tgz
          asset_content_type: application/tgz
          
      - name: Upload lua51 bin_lua51
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin_lua51_${{ github.event.inputs.tag_name }}.tgz
          asset_name: bin_lua51_${{ github.event.inputs.tag_name }}.tgz
          asset_content_type: application/tgz
          
